version: '3'
services:
  agriculture-core:
    image: agriculture-core
    container_name: agriculture-core
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/agriculture-core/
    tty: true